version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
    ports:
      - "4444:4444"
      
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2g'        
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '2g'   
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

      
  #sample service name just to run the tests 
  selenium-tests:
   image: sriramkukkadapu/selenium-docker
   depends_on: 
      - chrome
      - firefox
   environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=TestNG_Docker_Gird_Chrome_FireFox.xml
   volumes:
      - ./output:/usr/share/eclipse-workspace/test-output
      
      
  #sample service name just to run the tests 
  selenium-tests2:
   image: sriramkukkadapu/selenium-docker
   depends_on: 
      - chrome
      - firefox
   environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=TestNG_Docker_Gird_Chrome_FireFox.xml
   volumes:
      - ./output2:/usr/share/eclipse-workspace/test-output     
         

      
       
                       