# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Selenium Grid Example - Faisal Khatri

on:
  pull_request:
    branches:
      - master
      - issue-*

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: maven

      - name: Start Selenium Grid 4
        run: docker compose -f  ${{ github.workspace }}/docker-compose-v3.yml up --scale chrome=4 -d

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install Firefox
        uses: browser-actions/setup-firefox@latest

      - name: Run the tests
        run: |
          rm -rf ./test-output/*
          mvn clean test -Pweb  

      - name: Stop docker compose for Juice Shop and Selenium grid
        run: docker-compose -f ${{ github.workspace }}/docker-compose-v3.yml down --remove-orphans

      - name: Upload report artifact
        uses: actions/upload-artifact@v2
        with: 
          name: ${{ github.run_number }}-testng-report-upload
          path: ./test-output/
          if-no-files-found: ignore        


      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: test-output
