name: Run web tests in Github runner

on:

  schedule:
    # - cron:  '1 * * * *'
    - cron: '0 8 * * *'  #everday at 8 am    

  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
            version: 1.10.1
            args: -limit 10
            browsers: chrome
            last-versions: 1

      - name: checkout
        uses: actions/checkout@v2

      - name: Run the tests
        run: |
            rm -rf ./test-output/*
            mvn clean test -Pweb  
            #mvn clean test -Dsurefire.suiteXmlFiles=web-testng.xml

      - name: Upload report artifact
        uses: actions/upload-artifact@v2
        with: 
          name: ${{ github.run_number }}-testng-report-upload
          path: ./test-output/
          if-no-files-found: ignore        
          retention-days: 2

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: test-output

